# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ajacobs\Python\tools\dnd\UI\resources\\testWidget.ui',
# licensing of 'C:\Users\ajacobs\Python\tools\dnd\UI\resources\\testWidget.ui' applies.
#
# Created: Fri Mar 15 11:24:00 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 908)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 9, 184, 764))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statFrameStr = QtWidgets.QFrame(self.frame)
        self.statFrameStr.setFrameShape(QtWidgets.QFrame.Panel)
        self.statFrameStr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.statFrameStr.setObjectName("statFrameStr")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.statFrameStr)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.statLabelStr = QtWidgets.QLabel(self.statFrameStr)
        self.statLabelStr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statLabelStr.setAlignment(QtCore.Qt.AlignCenter)
        self.statLabelStr.setObjectName("statLabelStr")
        self.verticalLayout_2.addWidget(self.statLabelStr)
        self.valueHLayoutStr = QtWidgets.QHBoxLayout()
        self.valueHLayoutStr.setObjectName("valueHLayoutStr")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutStr.addItem(spacerItem)
        self.valueLineEditStr = QtWidgets.QLineEdit(self.statFrameStr)
        self.valueLineEditStr.setMinimumSize(QtCore.QSize(40, 40))
        self.valueLineEditStr.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setWeight(50)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.valueLineEditStr.setFont(font)
        self.valueLineEditStr.setMaxLength(2)
        self.valueLineEditStr.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLineEditStr.setObjectName("valueLineEditStr")
        self.valueHLayoutStr.addWidget(self.valueLineEditStr)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutStr.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.valueHLayoutStr)
        self.modHLayoutStr = QtWidgets.QHBoxLayout()
        self.modHLayoutStr.setObjectName("modHLayoutStr")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutStr.addItem(spacerItem2)
        self.modLineEditStr = QtWidgets.QLineEdit(self.statFrameStr)
        self.modLineEditStr.setMinimumSize(QtCore.QSize(30, 30))
        self.modLineEditStr.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.modLineEditStr.setFont(font)
        self.modLineEditStr.setMaxLength(2)
        self.modLineEditStr.setAlignment(QtCore.Qt.AlignCenter)
        self.modLineEditStr.setObjectName("modLineEditStr")
        self.modHLayoutStr.addWidget(self.modLineEditStr)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutStr.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.modHLayoutStr)
        self.verticalLayout.addWidget(self.statFrameStr)
        self.statFrameDex = QtWidgets.QFrame(self.frame)
        self.statFrameDex.setFrameShape(QtWidgets.QFrame.Panel)
        self.statFrameDex.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.statFrameDex.setObjectName("statFrameDex")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.statFrameDex)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.statLabelDex = QtWidgets.QLabel(self.statFrameDex)
        self.statLabelDex.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statLabelDex.setAlignment(QtCore.Qt.AlignCenter)
        self.statLabelDex.setObjectName("statLabelDex")
        self.verticalLayout_3.addWidget(self.statLabelDex)
        self.valueHLayoutDex = QtWidgets.QHBoxLayout()
        self.valueHLayoutDex.setObjectName("valueHLayoutDex")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutDex.addItem(spacerItem4)
        self.valueLineEditDex = QtWidgets.QLineEdit(self.statFrameDex)
        self.valueLineEditDex.setMinimumSize(QtCore.QSize(40, 40))
        self.valueLineEditDex.setMaximumSize(QtCore.QSize(50, 50))
        self.valueLineEditDex.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLineEditDex.setObjectName("valueLineEditDex")
        self.valueHLayoutDex.addWidget(self.valueLineEditDex)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutDex.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.valueHLayoutDex)
        self.modHLayoutDex = QtWidgets.QHBoxLayout()
        self.modHLayoutDex.setObjectName("modHLayoutDex")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutDex.addItem(spacerItem6)
        self.modLineEditDex = QtWidgets.QLineEdit(self.statFrameDex)
        self.modLineEditDex.setMinimumSize(QtCore.QSize(30, 30))
        self.modLineEditDex.setMaximumSize(QtCore.QSize(30, 30))
        self.modLineEditDex.setAlignment(QtCore.Qt.AlignCenter)
        self.modLineEditDex.setObjectName("modLineEditDex")
        self.modHLayoutDex.addWidget(self.modLineEditDex)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutDex.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.modHLayoutDex)
        self.verticalLayout.addWidget(self.statFrameDex)
        self.statFrameCon = QtWidgets.QFrame(self.frame)
        self.statFrameCon.setFrameShape(QtWidgets.QFrame.Panel)
        self.statFrameCon.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.statFrameCon.setObjectName("statFrameCon")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.statFrameCon)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.statLabelCon = QtWidgets.QLabel(self.statFrameCon)
        self.statLabelCon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statLabelCon.setAlignment(QtCore.Qt.AlignCenter)
        self.statLabelCon.setObjectName("statLabelCon")
        self.verticalLayout_7.addWidget(self.statLabelCon)
        self.valueHLayoutCon = QtWidgets.QHBoxLayout()
        self.valueHLayoutCon.setObjectName("valueHLayoutCon")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutCon.addItem(spacerItem8)
        self.valueLineEditCon = QtWidgets.QLineEdit(self.statFrameCon)
        self.valueLineEditCon.setMinimumSize(QtCore.QSize(40, 40))
        self.valueLineEditCon.setMaximumSize(QtCore.QSize(50, 50))
        self.valueLineEditCon.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLineEditCon.setObjectName("valueLineEditCon")
        self.valueHLayoutCon.addWidget(self.valueLineEditCon)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutCon.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.valueHLayoutCon)
        self.modHLayoutCon = QtWidgets.QHBoxLayout()
        self.modHLayoutCon.setObjectName("modHLayoutCon")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutCon.addItem(spacerItem10)
        self.modLineEditCon = QtWidgets.QLineEdit(self.statFrameCon)
        self.modLineEditCon.setMinimumSize(QtCore.QSize(30, 30))
        self.modLineEditCon.setMaximumSize(QtCore.QSize(30, 30))
        self.modLineEditCon.setAlignment(QtCore.Qt.AlignCenter)
        self.modLineEditCon.setObjectName("modLineEditCon")
        self.modHLayoutCon.addWidget(self.modLineEditCon)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutCon.addItem(spacerItem11)
        self.verticalLayout_7.addLayout(self.modHLayoutCon)
        self.verticalLayout.addWidget(self.statFrameCon)
        self.statFrameInt = QtWidgets.QFrame(self.frame)
        self.statFrameInt.setFrameShape(QtWidgets.QFrame.Panel)
        self.statFrameInt.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.statFrameInt.setObjectName("statFrameInt")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.statFrameInt)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.statLabelInt = QtWidgets.QLabel(self.statFrameInt)
        self.statLabelInt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statLabelInt.setAlignment(QtCore.Qt.AlignCenter)
        self.statLabelInt.setObjectName("statLabelInt")
        self.verticalLayout_4.addWidget(self.statLabelInt)
        self.valueHLayoutInt = QtWidgets.QHBoxLayout()
        self.valueHLayoutInt.setObjectName("valueHLayoutInt")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutInt.addItem(spacerItem12)
        self.valueLineEditInt = QtWidgets.QLineEdit(self.statFrameInt)
        self.valueLineEditInt.setMinimumSize(QtCore.QSize(40, 40))
        self.valueLineEditInt.setMaximumSize(QtCore.QSize(50, 50))
        self.valueLineEditInt.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLineEditInt.setObjectName("valueLineEditInt")
        self.valueHLayoutInt.addWidget(self.valueLineEditInt)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutInt.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.valueHLayoutInt)
        self.modHLayoutInt = QtWidgets.QHBoxLayout()
        self.modHLayoutInt.setObjectName("modHLayoutInt")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutInt.addItem(spacerItem14)
        self.modLineEditInt = QtWidgets.QLineEdit(self.statFrameInt)
        self.modLineEditInt.setMinimumSize(QtCore.QSize(30, 30))
        self.modLineEditInt.setMaximumSize(QtCore.QSize(30, 30))
        self.modLineEditInt.setAlignment(QtCore.Qt.AlignCenter)
        self.modLineEditInt.setObjectName("modLineEditInt")
        self.modHLayoutInt.addWidget(self.modLineEditInt)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutInt.addItem(spacerItem15)
        self.verticalLayout_4.addLayout(self.modHLayoutInt)
        self.verticalLayout.addWidget(self.statFrameInt)
        self.statFrameWis = QtWidgets.QFrame(self.frame)
        self.statFrameWis.setFrameShape(QtWidgets.QFrame.Panel)
        self.statFrameWis.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.statFrameWis.setObjectName("statFrameWis")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.statFrameWis)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.statLabelWis = QtWidgets.QLabel(self.statFrameWis)
        self.statLabelWis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statLabelWis.setAlignment(QtCore.Qt.AlignCenter)
        self.statLabelWis.setObjectName("statLabelWis")
        self.verticalLayout_5.addWidget(self.statLabelWis)
        self.valueHLayoutWis = QtWidgets.QHBoxLayout()
        self.valueHLayoutWis.setObjectName("valueHLayoutWis")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutWis.addItem(spacerItem16)
        self.valueLineEditWis = QtWidgets.QLineEdit(self.statFrameWis)
        self.valueLineEditWis.setMinimumSize(QtCore.QSize(40, 40))
        self.valueLineEditWis.setMaximumSize(QtCore.QSize(50, 50))
        self.valueLineEditWis.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLineEditWis.setObjectName("valueLineEditWis")
        self.valueHLayoutWis.addWidget(self.valueLineEditWis)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutWis.addItem(spacerItem17)
        self.verticalLayout_5.addLayout(self.valueHLayoutWis)
        self.modHLayoutWis = QtWidgets.QHBoxLayout()
        self.modHLayoutWis.setObjectName("modHLayoutWis")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutWis.addItem(spacerItem18)
        self.modLineEditWis = QtWidgets.QLineEdit(self.statFrameWis)
        self.modLineEditWis.setMinimumSize(QtCore.QSize(30, 30))
        self.modLineEditWis.setMaximumSize(QtCore.QSize(30, 30))
        self.modLineEditWis.setAlignment(QtCore.Qt.AlignCenter)
        self.modLineEditWis.setObjectName("modLineEditWis")
        self.modHLayoutWis.addWidget(self.modLineEditWis)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutWis.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.modHLayoutWis)
        self.verticalLayout.addWidget(self.statFrameWis)
        self.statFrameCha = QtWidgets.QFrame(self.frame)
        self.statFrameCha.setFrameShape(QtWidgets.QFrame.Panel)
        self.statFrameCha.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.statFrameCha.setObjectName("statFrameCha")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.statFrameCha)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.statLabelCha = QtWidgets.QLabel(self.statFrameCha)
        self.statLabelCha.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statLabelCha.setAlignment(QtCore.Qt.AlignCenter)
        self.statLabelCha.setObjectName("statLabelCha")
        self.verticalLayout_6.addWidget(self.statLabelCha)
        self.valueHLayoutCha = QtWidgets.QHBoxLayout()
        self.valueHLayoutCha.setObjectName("valueHLayoutCha")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutCha.addItem(spacerItem20)
        self.valueLineEditCha = QtWidgets.QLineEdit(self.statFrameCha)
        self.valueLineEditCha.setMinimumSize(QtCore.QSize(40, 40))
        self.valueLineEditCha.setMaximumSize(QtCore.QSize(50, 50))
        self.valueLineEditCha.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLineEditCha.setObjectName("valueLineEditCha")
        self.valueHLayoutCha.addWidget(self.valueLineEditCha)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.valueHLayoutCha.addItem(spacerItem21)
        self.verticalLayout_6.addLayout(self.valueHLayoutCha)
        self.modHLayoutCha = QtWidgets.QHBoxLayout()
        self.modHLayoutCha.setObjectName("modHLayoutCha")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutCha.addItem(spacerItem22)
        self.modLineEditCha = QtWidgets.QLineEdit(self.statFrameCha)
        self.modLineEditCha.setMinimumSize(QtCore.QSize(30, 30))
        self.modLineEditCha.setMaximumSize(QtCore.QSize(30, 30))
        self.modLineEditCha.setAlignment(QtCore.Qt.AlignCenter)
        self.modLineEditCha.setObjectName("modLineEditCha")
        self.modHLayoutCha.addWidget(self.modLineEditCha)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modHLayoutCha.addItem(spacerItem23)
        self.verticalLayout_6.addLayout(self.modHLayoutCha)
        self.verticalLayout.addWidget(self.statFrameCha)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(260, 80, 200, 91))
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(19, 19))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(19, 19))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setMaxLength(2)
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(22, 22))
        self.lineEdit.setMaximumSize(QtCore.QSize(22, 22))
        self.lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setMaxLength(2)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 50))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(28, 0))
        self.label.setMaximumSize(QtCore.QSize(28, 20))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_8.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        print ('cat')
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 865, 21))
        self.menubar.setObjectName("menubar")
        
        self.menudropDownMenu = QtWidgets.QMenu(self.menubar)
        self.menudropDownMenu.setObjectName("menudropDownMenu")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.actiondropDownMenuItem = QtWidgets.QAction(MainWindow)
        self.actiondropDownMenuItem.setObjectName("actiondropDownMenuItem")
        self.menudropDownMenu.addAction(self.actiondropDownMenuItem)
        self.menubar.addAction(self.menudropDownMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.statLabelStr.setText(QtWidgets.QApplication.translate("MainWindow", "thisTextHeere", None, -1))
        self.valueLineEditStr.setText(QtWidgets.QApplication.translate("MainWindow", "12", None, -1))
        self.modLineEditStr.setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.statLabelDex.setText(QtWidgets.QApplication.translate("MainWindow", "thisTextHeere", None, -1))
        self.statLabelCon.setText(QtWidgets.QApplication.translate("MainWindow", "thisTextHeere", None, -1))
        self.statLabelInt.setText(QtWidgets.QApplication.translate("MainWindow", "thisTextHeere", None, -1))
        self.statLabelWis.setText(QtWidgets.QApplication.translate("MainWindow", "thisTextHeere", None, -1))
        self.statLabelCha.setText(QtWidgets.QApplication.translate("MainWindow", "thisTextHeere", None, -1))
        self.lineEdit_2.setText(QtWidgets.QApplication.translate("MainWindow", "PE", None, -1))
        self.lineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "12", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Animal Handling", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "(Dex)", None, -1))
        self.menudropDownMenu.setTitle(QtWidgets.QApplication.translate("MainWindow", "dropDownMenu", None, -1))
        self.actiondropDownMenuItem.setText(QtWidgets.QApplication.translate("MainWindow", "dropDownMenuItem", None, -1))

